name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.18.0   

    - name: Install React dependencies
      working-directory: ./movieverse.client
      run: npm install

    - name: Build React app
      working-directory: ./movieverse.client
      run: npm run build

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build .NET project
      run: dotnet build --no-restore --configuration Release

    - name: Run .NET tests
      run: dotnet test --no-build --verbosity normal
